import type { Metadata } from 'next';
import { Inter } from 'next/font/google'; // Import Inter from Google Fonts
import localFont from 'next/font/local';
import './globals.css';
import Navbar from '@/shared/Navbar/Navbar';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} font-sans antialiased bg-[#F8F8F8]`}
      >
        <div className="min-h-screen flex flex-col items-center">
          <Navbar />
          <main className="w-full px-4 sm:px-8 md:px-16 lg:px-24 xl:px-[120px]">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
